// src/components/Navbar.tsx
import React from "react"
import Link from "next/link"
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuIndicator,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    navigationMenuTriggerStyle,
    NavigationMenuViewport
} from "@/components/ui/navigation-menu"

export default function Navbar() {
    return (
        <div className="md:px-20 md:mt-4" >
            <div className=" md:px-20  w-full text-xl flex justify-between items-center rounded-md border  md:min-h-18 bg-gradient-to-r from-secondary to-primary text-white shadow-md backdrop-blur-md
">
                <div className="text-5xl text-primary   ">
                    dn.
                </div>
                <NavigationMenu >
                    <NavigationMenuList className="flex justify-around bg-none text-2xl">
                        <NavigationMenuItem >
                            <NavigationMenuLink asChild   >
                                <Link href="/home" className="hover:underline" >Home</Link>
                            </NavigationMenuLink>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <NavigationMenuLink asChild >
                                <Link href="/experiences" className="hover:underline">Experiences</Link>
                            </NavigationMenuLink>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <NavigationMenuLink asChild >
                                <Link href="/products" className="hover:underline">Products</Link>
                            </NavigationMenuLink>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <NavigationMenuLink asChild >
                                <Link href="/" className="hover:underline">Contact me </Link>
                            </NavigationMenuLink>
                        </NavigationMenuItem>
                    </NavigationMenuList>
                </NavigationMenu>
            </div>
        </div>)

}

// src/lib/components/navbar.svelte
<script>
	let buttonStyles = 'rounded-md bg-slate-700 px-3 hover:cursor-pointer';
</script>

<nav>
	<div
		class="mx-1 flex
         items-center justify-between rounded-md px-3 py-2 text-white md:mx-3 md:my-2"
	>
		<div>
			<h2 class="font-[audiowide] text-3xl">dn.</h2>
		</div>
		<div class="flex items-center justify-around gap-3 font-[orbitron]">
			<button class={buttonStyles}>Home </button>
			<button class={buttonStyles}>Products </button>
			<button class={buttonStyles}>Contact Me</button>
		</div>
	</div>
</nav>
